project:
  type: book
  output-dir: docs
engine: knitr
filters:
  - glossary

book:
  title: "Linear Regression and Model Selection with R"
  chapters:
    - index.qmd
    - ch0-lm.qmd
    - ch1-slr.qmd
    - ch2-mlr.qmd
    - ch3-model-building.qmd
    - ch4-pitfalls-diagnostics-remedies.qmd
    - ch5-case-naplan.qmd
    - glossary.qmd
  page-navigation: false
format:
  live-html:
    toc: true
    number-sections: true
    toc-depth: 2
    toc-expand: 3
    toc-title: Contents
    number-depth: 4

css: 
 - include/webex.css
 - include/style.css
include-after-body:
 - include/webex.js
 - include/displayall.js
 - include/gating.js
 - include/skip-exercises.js
