project:
  type: book
  output-dir: docs
engine: knitr

book:
  title: "Linear Regression and Model Selection with R"
  chapters:
    - index.qmd
    - module00-lm.qmd
    - module01-slr.qmd
    - module02-mlr.qmd
    - module03-model-building.qmd
    - module04-regression-pitfalls-diagnostics.qmd
    - module05-case-naplan.qmd
    - glossary.qmd
  page-navigation: false
format:
  live-html:
    toc: true
    number-sections: true
    toc-depth: 1
    toc-expand: 2
    toc-title: Contents
    number-depth: 2

css: 
 - include/webex.css
 - include/style.css
include-after-body:
 - include/webex.js
 - include/displayall.js
 - include/gating.js
 - include/skip-exercises.js
