project:
  type: book
  output-dir: docs
engine: knitr

book:
  title: Introduction to Linear Regression in R
  chapters:
  - index.qmd
  - part: SimpleLinearRegression.qmd
    chapters:
    - LinearModels.qmd
    - SLRFitting.qmd
    - SLRDiagnostics.qmd
    - SLRInference.qmd
    - SLRCase.qmd
  - part: MultipleRegression.qmd
    chapters:
      - MLRNewFeatures.qmd
      - MLRDerivedFeatures.qmd
      - VariableScreening.qmd
  - RegressionCaseStudy.qmd
  - glossary.qmd
  page-navigation: false
format:
  live-html:
    toc: true
    number-sections: true
    toc-depth: 1
    toc-expand: 2
    toc-title: Contents
    number-depth: 2

css: 
 - include/webex.css
 - include/style.css
include-after-body:
 - include/webex.js
 - include/displayall.js
 - include/gating.js
 - include/skip-exercises.js
